export const allLanguages = [
  { label: 'Afaraf', value: 'aa' },
  { label: 'Afrikaans', value: 'af' },
  { label: 'Akan', value: 'ak' },
  { label: 'Shqip', value: 'sq' },
  { label: 'አማርኛ', value: 'am' },
  { label: 'العربية', value: 'ar' },
  { label: 'Aragonés', value: 'an' },
  { label: 'Հայերեն', value: 'hy' },
  { label: 'অসমীয়া', value: 'as' },
  { label: 'Avarca', value: 'av' },
  { label: 'Aymar aru', value: 'ay' },
  { label: 'Azərbaycan dili', value: 'az' },

  { label: 'Bashkir', value: 'ba' },
  { label: 'Български', value: 'bg' },
  { label: 'भोजपुरी', value: 'bh' },
  { label: 'Bislama', value: 'bi' },
  { label: 'বাংলা', value: 'bn' },
  { label: 'བོད་ཡིག', value: 'bo' },
  { label: 'Bosanski', value: 'bs' },
  { label: 'Brezhoneg', value: 'br' },

  { label: 'Català', value: 'ca' },
  { label: 'Čeština', value: 'cs' },
  { label: 'Чӑвашла', value: 'cv' },
  { label: 'Cymraeg', value: 'cy' },

  { label: 'Dansk', value: 'da' },
  { label: 'Deutsch', value: 'de' },
  { label: 'ދިވެހި', value: 'dv' },

  { label: 'Ελληνικά', value: 'el' },
  { label: 'English', value: 'en' },
  { label: 'Esperanto', value: 'eo' },
  { label: 'Español', value: 'es' },
  { label: 'Eesti', value: 'et' },
  { label: 'Euskara', value: 'eu' },

  { label: 'فارسی', value: 'fa' },
  { label: 'Suomi', value: 'fi' },
  { label: 'Fijian', value: 'fj' },
  { label: 'Føroyskt', value: 'fo' },
  { label: 'Français', value: 'fr' },
  { label: 'Frysk', value: 'fy' },

  { label: 'Gaeilge', value: 'ga' },
  { label: 'Gàidhlig', value: 'gd' },
  { label: 'Galego', value: 'gl' },
  { label: 'ગુજરાતી', value: 'gu' },

  { label: 'Hausa', value: 'ha' },
  { label: 'עברית', value: 'he' },
  { label: 'हिन्दी', value: 'hi' },
  { label: 'Hrvatski', value: 'hr' },
  { label: 'Magyar', value: 'hu' },

  { label: 'Հայերեն', value: 'hy' },

  { label: 'Bahasa Indonesia', value: 'id' },
  { label: 'Íslenska', value: 'is' },
  { label: 'Italiano', value: 'it' },

  { label: '日本語', value: 'ja' },
  { label: 'ქართული', value: 'ka' },
  { label: 'Қазақ тілі', value: 'kk' },
  { label: 'ភាសាខ្មែរ', value: 'km' },
  { label: '한국어', value: 'ko' },
  { label: 'Kurdî', value: 'ku' },
  { label: 'Кыргызча', value: 'ky' },

  { label: 'Latina', value: 'la' },
  { label: 'Lëtzebuergesch', value: 'lb' },
  { label: 'Lietuvių', value: 'lt' },
  { label: 'Latviešu', value: 'lv' },

  { label: 'Македонски', value: 'mk' },
  { label: 'മലയാളം', value: 'ml' },
  { label: 'Монгол', value: 'mn' },
  { label: 'मराठी', value: 'mr' },
  { label: 'Bahasa Melayu', value: 'ms' },
  { label: 'Malti', value: 'mt' },
  { label: 'မြန်မာဘာသာ', value: 'my' },

  { label: 'Norsk Bokmål', value: 'nb' },
  { label: 'नेपाली', value: 'ne' },
  { label: 'Nederlands', value: 'nl' },
  { label: 'Norsk Nynorsk', value: 'nn' },

  { label: 'Occitan', value: 'oc' },

  { label: 'ਪੰਜਾਬੀ', value: 'pa' },
  { label: 'Polski', value: 'pl' },
  { label: 'Português', value: 'pt' },

  { label: 'Română', value: 'ro' },
  { label: 'Русский', value: 'ru' },

  { label: 'संस्कृतम्', value: 'sa' },
  { label: 'Slovenčina', value: 'sk' },
  { label: 'Slovenščina', value: 'sl' },
  { label: 'Shqip', value: 'sq' },
  { label: 'Српски', value: 'sr' },
  { label: 'Svenska', value: 'sv' },
  { label: 'Kiswahili', value: 'sw' },

  { label: 'தமிழ்', value: 'ta' },
  { label: 'తెలుగు', value: 'te' },
  { label: 'ไทย', value: 'th' },
  { label: 'Türkçe', value: 'tr' },

  { label: 'Українська', value: 'uk' },
  { label: 'اردو', value: 'ur' },

  { label: 'Tiếng Việt', value: 'vi' },

  { label: '中文', value: 'zh' },
  { label: 'isiZulu', value: 'zu' }
];

export const languageList = [
  { label: 'Afar', value: 'aa' },
  { label: 'Abkhazian', value: 'ab' },
  { label: 'Avestan', value: 'ae' },
  { label: 'Afrikaans', value: 'af' },
  { label: 'Akan', value: 'ak' },
  { label: 'Amharic', value: 'am' },
  { label: 'Aragonese', value: 'an' },
  { label: 'Arabic', value: 'ar' },
  { label: 'Assamese', value: 'as' },
  { label: 'Avaric', value: 'av' },
  { label: 'Aymara', value: 'ay' },
  { label: 'Azerbaijani', value: 'az' },

  { label: 'Bashkir', value: 'ba' },
  { label: 'Belarusian', value: 'be' },
  { label: 'Bulgarian', value: 'bg' },
  { label: 'Bihari', value: 'bh' },
  { label: 'Bislama', value: 'bi' },
  { label: 'Bambara', value: 'bm' },
  { label: 'Bengali', value: 'bn' },
  { label: 'Tibetan', value: 'bo' },
  { label: 'Breton', value: 'br' },
  { label: 'Bosnian', value: 'bs' },

  { label: 'Catalan', value: 'ca' },
  { label: 'Chechen', value: 'ce' },
  { label: 'Chamorro', value: 'ch' },
  { label: 'Corsican', value: 'co' },
  { label: 'Cree', value: 'cr' },
  { label: 'Czech', value: 'cs' },
  { label: 'Church Slavic', value: 'cu' },
  { label: 'Chuvash', value: 'cv' },
  { label: 'Welsh', value: 'cy' },

  { label: 'Danish', value: 'da' },
  { label: 'German', value: 'de' },
  { label: 'Divehi', value: 'dv' },

  { label: 'Dzongkha', value: 'dz' },

  { label: 'Greek', value: 'el' },
  { label: 'English', value: 'en' },
  { label: 'Esperanto', value: 'eo' },
  { label: 'Spanish', value: 'es' },
  { label: 'Estonian', value: 'et' },
  { label: 'Basque', value: 'eu' },

  { label: 'Persian', value: 'fa' },
  { label: 'Fulah', value: 'ff' },
  { label: 'Finnish', value: 'fi' },
  { label: 'Fijian', value: 'fj' },
  { label: 'Faroese', value: 'fo' },
  { label: 'French', value: 'fr' },
  { label: 'Western Frisian', value: 'fy' },

  { label: 'Irish', value: 'ga' },
  { label: 'Scottish Gaelic', value: 'gd' },
  { label: 'Galician', value: 'gl' },
  { label: 'Guarani', value: 'gn' },
  { label: 'Gujarati', value: 'gu' },

  { label: 'Hausa', value: 'ha' },
  { label: 'Hebrew', value: 'he' },
  { label: 'Hindi', value: 'hi' },
  { label: 'Hiri Motu', value: 'ho' },
  { label: 'Croatian', value: 'hr' },
  { label: 'Haitian', value: 'ht' },
  { label: 'Hungarian', value: 'hu' },

  { label: 'Armenian', value: 'hy' },

  { label: 'Herero', value: 'hz' },

  { label: 'Interlingua', value: 'ia' },
  { label: 'Indonesian', value: 'id' },
  { label: 'Interlingue', value: 'ie' },
  { label: 'Igbo', value: 'ig' },
  { label: 'Inupiaq', value: 'ik' },
  { label: 'Ido', value: 'io' },
  { label: 'Icelandic', value: 'is' },
  { label: 'Italian', value: 'it' },

  { label: 'Inuktitut', value: 'iu' },

  { label: 'Japanese', value: 'ja' },
  { label: 'Javanese', value: 'jv' },

  { label: 'Georgian', value: 'ka' },
  { label: 'Kongo', value: 'kg' },
  { label: 'Kikuyu', value: 'ki' },
  { label: 'Kwanyama', value: 'kj' },
  { label: 'Kazakh', value: 'kk' },
  { label: 'Kalaallisut', value: 'kl' },
  { label: 'Khmer', value: 'km' },
  { label: 'Kannada', value: 'kn' },
  { label: 'Korean', value: 'ko' },
  { label: 'Kanuri', value: 'kr' },
  { label: 'Kashmiri', value: 'ks' },
  { label: 'Kurdish', value: 'ku' },
  { label: 'Komi', value: 'kv' },
  { label: 'Cornish', value: 'kw' },
  { label: 'Kirghiz', value: 'ky' },

  { label: 'Latin', value: 'la' },
  { label: 'Luxembourgish', value: 'lb' },
  { label: 'Ganda', value: 'lg' },
  { label: 'Limburgish', value: 'li' },
  { label: 'Lingala', value: 'ln' },
  { label: 'Lao', value: 'lo' },
  { label: 'Lithuanian', value: 'lt' },
  { label: 'Luba-Katanga', value: 'lu' },
  { label: 'Latvian', value: 'lv' },

  { label: 'Manx', value: 'gv' },
  { label: 'Macedonian', value: 'mk' },
  { label: 'Malayalam', value: 'ml' },
  { label: 'Mongolian', value: 'mn' },
  { label: 'Marathi', value: 'mr' },
  { label: 'Malay', value: 'ms' },
  { label: 'Maltese', value: 'mt' },
  { label: 'Burmese', value: 'my' },

  { label: 'Nauru', value: 'na' },
  { label: 'Norwegian Bokmål', value: 'nb' },
  { label: 'North Ndebele', value: 'nd' },
  { label: 'Nepali', value: 'ne' },
  { label: 'Ndonga', value: 'ng' },
  { label: 'Dutch', value: 'nl' },
  { label: 'Norwegian Nynorsk', value: 'nn' },
  { label: 'Norwegian', value: 'no' },

  { label: 'Occitan', value: 'oc' },
  { label: 'Ojibwa', value: 'oj' },
  { label: 'Oromo', value: 'om' },
  { label: 'Oriya', value: 'or' },
  { label: 'Ossetian', value: 'os' },

  { label: 'Punjabi', value: 'pa' },
  { label: 'Pali', value: 'pi' },
  { label: 'Polish', value: 'pl' },
  { label: 'Pashto', value: 'ps' },
  { label: 'Portuguese', value: 'pt' },

  { label: 'Quechua', value: 'qu' },

  { label: 'Romansh', value: 'rm' },
  { label: 'Kirundi', value: 'rn' },
  { label: 'Romanian', value: 'ro' },
  { label: 'Russian', value: 'ru' },

  { label: 'Sanskrit', value: 'sa' },
  { label: 'Sardinian', value: 'sc' },
  { label: 'Sindhi', value: 'sd' },
  { label: 'Northern Sami', value: 'se' },
  { label: 'Sango', value: 'sg' },
  { label: 'Sinhala', value: 'si' },
  { label: 'Slovak', value: 'sk' },
  { label: 'Slovenian', value: 'sl' },
  { label: 'Samoan', value: 'sm' },
  { label: 'Shona', value: 'sn' },
  { label: 'Somali', value: 'so' },
  { label: 'Albanian', value: 'sq' },
  { label: 'Serbian', value: 'sr' },
  { label: 'Swati', value: 'ss' },
  { label: 'Southern Sotho', value: 'st' },
  { label: 'Sundanese', value: 'su' },
  { label: 'Swedish', value: 'sv' },
  { label: 'Swahili', value: 'sw' },

  { label: 'Tamil', value: 'ta' },
  { label: 'Telugu', value: 'te' },
  { label: 'Tajik', value: 'tg' },
  { label: 'Thai', value: 'th' },
  { label: 'Tigrinya', value: 'ti' },
  { label: 'Turkmen', value: 'tk' },
  { label: 'Tagalog', value: 'tl' },
  { label: 'Tswana', value: 'tn' },
  { label: 'Tonga', value: 'to' },
  { label: 'Turkish', value: 'tr' },
  { label: 'Tsonga', value: 'ts' },
  { label: 'Tatar', value: 'tt' },
  { label: 'Twi', value: 'tw' },

  { label: 'Tahitian', value: 'ty' },

  { label: 'Uighur', value: 'ug' },
  { label: 'Ukrainian', value: 'uk' },
  { label: 'Urdu', value: 'ur' },
  { label: 'Uzbek', value: 'uz' },

  { label: 'Venda', value: 've' },
  { label: 'Vietnamese', value: 'vi' },
  { label: 'Volapük', value: 'vo' },

  { label: 'Walloon', value: 'wa' },
  { label: 'Wolof', value: 'wo' },

  { label: 'Xhosa', value: 'xh' },

  { label: 'Yiddish', value: 'yi' },
  { label: 'Yoruba', value: 'yo' },

  { label: 'Zhuang', value: 'za' },
  { label: 'Chinese', value: 'zh' },
  { label: 'Zulu', value: 'zu' }
];
