const WRAPHEIGHT = 54;
const INPUTHEIGHT = 32;
const BORDERRADIUS = 4;
const BGCOLOR = 'transparent';
const INPUT_INNER_PADDING = 14;
const LINE_HEIGHT = 1.57;

export {
  BGCOLOR,
  BORDERRADIUS,
  INPUTHEIGHT,
  INPUT_INNER_PADDING,
  LINE_HEIGHT,
  WRAPHEIGHT
};
