// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

const LogoIcon: React.FC = () => {
  return (
    <img
      src="https://www.seal.io/Public/Uploads/uploadfile/images/20230825/a1logo1244.svg"
      alt="logo"
      style={{ height: 24 }}
    />
  );
};

export default LogoIcon;
