import IconFont from '@/components/icon-font';
import {
  ApiOutlined,
  CopyOutlined,
  DeleteOutlined,
  DockerOutlined,
  DownloadOutlined,
  EditOutlined,
  ExperimentOutlined,
  FileTextOutlined,
  KubernetesOutlined,
  ProfileOutlined,
  RetweetOutlined,
  StarOutlined,
  ThunderboltOutlined
} from '@ant-design/icons';
import React from 'react';

const icons = {
  EditOutlined: React.createElement(EditOutlined),
  ExperimentOutlined: React.createElement(ExperimentOutlined),
  DeleteOutlined: React.createElement(DeleteOutlined),
  ThunderboltOutlined: React.createElement(ThunderboltOutlined),
  RetweetOutlined: React.createElement(RetweetOutlined),
  DownloadOutlined: React.createElement(DownloadOutlined),
  FileTextOutlined: React.createElement(FileTextOutlined),
  ApiOutlined: React.createElement(ApiOutlined),
  KubernetesOutlined: React.createElement(KubernetesOutlined),
  ProfileOutlined: React.createElement(ProfileOutlined),
  DockerOutlined: React.createElement(DockerOutlined),
  Stop: React.createElement(IconFont, { type: 'icon-stop1' }),
  Play: React.createElement(IconFont, { type: 'icon-outline-play' }),
  Catalog: React.createElement(IconFont, { type: 'icon-catalog' }),
  HF: React.createElement(IconFont, { type: 'icon-huggingface' }),
  Ollama: React.createElement(IconFont, { type: 'icon-ollama' }),
  ModelScope: React.createElement(IconFont, { type: 'icon-tu2' }),
  LocalPath: React.createElement(IconFont, { type: 'icon-hard-disk' }),
  Launch: React.createElement(IconFont, { type: 'icon-rocket-launch' }),
  Deployment: React.createElement(IconFont, { type: 'icon-rocket-launch1' }),
  Docker: React.createElement(IconFont, { type: 'icon-docker' }),
  DigitalOcean: React.createElement(IconFont, { type: 'icon-digitalocean' }),
  DetailInfo: React.createElement(IconFont, { type: 'icon-detail-info' }),
  HuaweiCloud: React.createElement(IconFont, { type: 'icon-huaweicloud' }),
  AliCloud: React.createElement(IconFont, { type: 'icon-alicloud' }),
  TencentCloud: React.createElement(IconFont, { type: 'icon-tencentcloud' }),
  Nvidia: React.createElement(IconFont, { type: 'icon-nvidia' }),
  Ascend: React.createElement(IconFont, { type: 'icon-ascend' }),
  Catalog1: React.createElement(IconFont, { type: 'icon-catalog1' }),
  AMD: React.createElement(IconFont, { type: 'icon-amd' }),
  KubernetesFilled: React.createElement(IconFont, { type: 'icon-k8s-filled' }),
  EditContent: React.createElement(IconFont, { type: 'icon-edit-content' }),
  Yaml: React.createElement(IconFont, { type: 'icon-code_block' }),
  Version: React.createElement(IconFont, { type: 'icon-version' }),
  Parameter: React.createElement(IconFont, { type: 'icon-parameters' }),
  Private: React.createElement(IconFont, { type: 'icon-private' }),
  AWS: React.createElement(IconFont, { type: 'icon-aws' }),
  LockOpenRight: React.createElement(IconFont, {
    type: 'icon-lock_open_right'
  }),
  LockPerson: React.createElement(IconFont, { type: 'icon-lock_person' }),
  LockOpen: React.createElement(IconFont, { type: 'icon-lock_open' }),
  Permission: React.createElement(IconFont, { type: 'icon-permission' }),
  CaptivePortal: React.createElement(IconFont, { type: 'icon-captive_portal' }),
  StarOutlined: React.createElement(StarOutlined),
  Charger: React.createElement(IconFont, { type: 'icon-charger' }),
  Disabled: React.createElement(IconFont, { type: 'icon-disabled' }),
  CopyOutlined: React.createElement(CopyOutlined),
  Metrics: React.createElement(IconFont, { type: 'icon-metrics' })
};

export default icons;
